Repository JCSDA-internal/ufo-data, pull requests merged in 2021-06, with the labels that each got.

#8 New additional test files, 2020121500, for sfc/sonde data - needed for composite obs-operator tests
  testinput_tier_1/sfc_geoval_2020121500_s.nc
  testinput_tier_1/sfc_obs_2020121500_s.nc
  testinput_tier_1/sondes_geoval_2020121500_s.nc
  testinput_tier_1/sondes_obs_2020121500_s.nc
Labels: OBS1, OBS3

#13 New conventional data for 20201215, 00z cycle from new GSI-gdas-jedi changes
  testinput_tier_1/instruments/conventional/aircraft_geoval_2020121500_m.nc
  testinput_tier_1/instruments/conventional/aircraft_geoval_2020121500_s.nc
  testinput_tier_1/instruments/conventional/aircraft_obs_2020121500_m.nc
  testinput_tier_1/instruments/conventional/aircraft_obs_2020121500_s.nc
  testinput_tier_1/instruments/conventional/rass_tv_geoval_2020121500.nc
  testinput_tier_1/instruments/conventional/rass_tv_obs_2020121500.nc
  testinput_tier_1/instruments/conventional/satwind_geoval_2020121500_m.nc
  testinput_tier_1/instruments/conventional/satwind_geoval_2020121500_s.nc
  testinput_tier_1/instruments/conventional/satwind_obs_2020121500_m.nc
  testinput_tier_1/instruments/conventional/satwind_obs_2020121500_s.nc
  testinput_tier_1/instruments/conventional/scatwind_geoval_2020121500_m.nc
  testinput_tier_1/instruments/conventional/scatwind_geoval_2020121500_s.nc
  testinput_tier_1/instruments/conventional/scatwind_obs_2020121500_m.nc
  testinput_tier_1/instruments/conventional/scatwind_obs_2020121500_s.nc
  testinput_tier_1/instruments/conventional/sfc_geoval_2020121500_m.nc
  testinput_tier_1/instruments/conventional/sfc_geoval_2020121500_s.nc
  testinput_tier_1/instruments/conventional/sfc_obs_2020121500_m.nc
  testinput_tier_1/instruments/conventional/sfc_obs_2020121500_s.nc
  testinput_tier_1/instruments/conventional/sfcship_geoval_2020121500_m.nc
  testinput_tier_1/instruments/conventional/sfcship_geoval_2020121500_s.nc
  testinput_tier_1/instruments/conventional/sfcship_obs_2020121500_m.nc
  testinput_tier_1/instruments/conventional/sfcship_obs_2020121500_s.nc
  testinput_tier_1/instruments/conventional/sondes_geoval_2020121500_m.nc
  testinput_tier_1/instruments/conventional/sondes_geoval_2020121500_s.nc
  testinput_tier_1/instruments/conventional/sondes_obs_2020121500_m.nc
  testinput_tier_1/instruments/conventional/sondes_obs_2020121500_s.nc
  testinput_tier_1/instruments/conventional/vadwind_geoval_2020121500.nc
  testinput_tier_1/instruments/conventional/vadwind_obs_2020121500.nc
  testinput_tier_1/sfc_geoval_2020121500_s.nc
  testinput_tier_1/sfc_obs_2020121500_s.nc
Labels: OBS3

#11 Feature/Td2Rh
  testinput_tier_1/met_office_conversion_td2Rh_surface.nc4
Labels: OBS3

#10 Add refractivity observations and geovals for Met Office operator
  testinput_tier_1/gnssro_geoval_2019123006_refractivity.nc4
  testinput_tier_1/gnssro_geoval_2019123006_refractivity_nopseudo.nc4
  testinput_tier_1/gnssro_obs_2019123006_refractivity.nc4
  testinput_tier_1/gnssro_obs_2019123006_refractivity_nopseudo.nc4
Labels: OBS1
