Repository JCSDA-internal/ufo-data, pull requests merged in 2021-08, with the labels that each got.

#36 Data bilinear interpolation DataExtractor support
  testinput_tier_1/drawvaluefromfile_advanced.nc
  testinput_tier_1/drawvaluefromfile_advanced2.nc
  testinput_tier_1/drawvaluefromfile_advanced3.nc
  testinput_tier_1/variable_assignment_testdata.nc
Labels: JEDI2, draft

#43 Feature/satwind pressure errors
  testinput_tier_1/satwind_obs_1d_2020100106_noinv.nc4
  testinput_tier_1/satwind_pressure_errors.nc4
Labels: waiting for another PR

#37 Test files for UFO PR#1385 Background Check with threshold relative to background error
  testinput_tier_1/background_errors_for_altimeter_test.nc4
  testinput_tier_1/sataltimeter_sla_testdata.nc4
Labels: waiting for another PR

#41 Test data to check DataExtractor linear and bilinear interpolation methods support 3D array use end-to-end
  testinput_tier_1/drawvaluefromfile_advanced4.nc
  testinput_tier_1/drawvaluefromfile_advanced5.nc
  testinput_tier_1/variable_assignment_testdata.nc
Labels: JEDI2
