Repository JCSDA-internal/ufo-data, pull requests merged in 2021-11, with the labels that each got.

#89 update for insitupm obs operator
  testinput_tier_1/airnow-v2a-2020081306-sub.nc
  testinput_tier_1/airnow_hofx_rrfs_cmaq_v2a_2020081306_sub_m_geovals_0000.nc
Labels: COMPO

#92 Add netcdf for mixing ratio 2 RH filter
  testinput_tier_1/mixRatio2RH_conversion_aircraft.nc4
  testinput_tier_1/mixRatio2RH_conversion_aircraft_nosupersat.nc4
Labels: update test data

#101 Update test geovals for removal of air_pressure_at_two_meters_above_surface
  testinput_tier_1/PStar_geovals_20210521T1200Z.nc4
  testinput_tier_1/amsr2_geovals_20191230T0000Z_100subset.nc4
  testinput_tier_1/atms_geovals_20200401T0000Z_10locs.nc4
  testinput_tier_1/geovals_atms_20191230T0000Z_benchmark.nc4
  testinput_tier_1/geovals_atms_20191230T0000Z_predictors.nc4
Labels: adaptation complete, OBS3
