Repository JCSDA-internal/ufo-data, pull requests merged in 2021-09, with the labels that each got.

#49 DataExtractorNetCDFBackend multiple payload support
  testinput_tier_1/drawvaluefromfile_advanced.nc
  testinput_tier_1/drawvaluefromfile_advanced2.nc
  testinput_tier_1/drawvaluefromfile_advanced3.nc
Labels: JEDI2

#53 Add profiles not belonging to the extended obs space to files used by buddy check tests
  testinput_tier_1/met_office_buddy_check_multi_level_diag_extended.nc
  testinput_tier_1/met_office_buddy_check_multi_level_extended.nc
Labels: ready for merge, OBS1

#59 Extrapolation testing for DrawValueFromFile
  testinput_tier_1/drawvaluefromfile_advanced4.nc
  testinput_tier_1/drawvaluefromfile_extrap.nc
  testinput_tier_1/drawvaluefromfile_extrap2d.nc
  testinput_tier_1/variable_assignment_testdata.nc
Labels: draft, JEDI2

#50 Add files for the ctest of new ufo ObsAodMetOffice
  testinput_tier_1/aod_geoval_20210521T1200Z_mo.nc4
  testinput_tier_1/aod_obs_20210521T1200Z_mo.nc4
Labels: enhancement

#54 Add sensor zenith angle correction transform unit test file.
  testinput_tier_1/szacorrection_unit_transforms_2021011500.nc4
Labels: OBS3

#63 Addition of ozone test files (from ompsnp_npp instrument) for QC steps
  testinput_tier_1/instruments/conventional/ompsnp_npp_geoval_2020121500.nc
  testinput_tier_1/instruments/conventional/ompsnp_npp_obs_2020121500.nc
Labels: needs review, OBS1
