Repository JCSDA-internal/ufo-data, pull requests merged in 2022-10, with the labels that each got.

#217 Test data for 'Average Observations To Model Levels' filter
  testinput_tier_1/oceanprofile_averageobs_testdata.nc4
Labels: coordinate merge

#221 Bugfix: Ocean Vertical Stability Check test data
  testinput_tier_1/ocean_vertical_stability_testdata.nc4
Labels: needs review

#226 Feature/hs 3 ch percentage err
  testinput_tier_1/gnssro_obs_2020050106_1dvar.nc4
Labels: OBS

#220 Test data for Buddy Check changes (2 length scales and anisotropy)
  testinput_tier_1/met_office_buddy_check_oceanprofile.nc4
Labels: needs review
