Repository JCSDA-internal/ufo-data, pull requests merged in 2022-05, with the labels that each got.

#160 Add onedvar test that stores transmittance
  testinput_tier_1/geovals_atovs_transmittance_20210701T1200Z.nc4
  testinput_tier_1/obs_atovs_transmittance_20210701T1200Z.nc4
Labels: OBS1

#115 Update amsr2 geolval and observational files
  testinput_tier_1/amsr2_gcom-w1_geoval_2020120100_m.nc4
  testinput_tier_1/amsr2_gcom-w1_obs_2020120100_m.nc4
  testinput_tier_1/amsr2_gcom-w1_tlapmean.txt
  testinput_tier_1/satbias_amsr2_gcom-w1.nc4
Labels: OBS1, JEDI-GEOS

#150 Updated 2d scat file with ambiguities as extra dimension
  testinput_tier_1/scatwind_obs_2d_2020100106.nc4
  testinput_tier_1/scatwind_obs_2d_wind_direction_2020100106.nc4
Labels: ready for merge
