Repository JCSDA-internal/ufo-data, pull requests merged in 2022-06, with the labels that each got.

#171 Add reference data for CloudCostFunction ObsFunction
  testinput_tier_1/atovs_metopb_obs_2021011512_rttov_scatt.nc4
  testinput_tier_1/geovals_atovs_20210115T1200Z_rttov_scatt.nc4
Labels: OBS1

#170 Update the IASI test files used with RTTOV
  testinput_tier_1/geovals_iasi_2021011500Z.nc4
  testinput_tier_1/iasi_metopb_obs_2021011500.nc4
Labels: coordinate merge, OBS3

#188 restore 'cris-fsr_npp_obs_2018041500_m.nc4' for mpas-jedi ctest
  testinput_tier_1/cris-fsr_npp_obs_2018041500_m.nc4
Labels: bug
