Repository JCSDA-internal/ufo-data, pull requests merged in 2022-01, with the labels that each got.

#125 Change rttov geoval files so that they are top to bottom
  testinput_tier_1/amsr2_geovals_20191230T0000Z_100subset.nc4
  testinput_tier_1/atms_geovals_20200401T0000Z_10locs.nc4
  testinput_tier_1/geovals_atms_20191230T0000Z_benchmark.nc4
  testinput_tier_1/geovals_atms_20191230T0000Z_predictors.nc4
  testinput_tier_1/geovals_atms_20191230T0000Z_predictors_reversed.nc4
  testinput_tier_1/geovals_ssmis_onedvar_20210701T1200Z.nc4
Labels: coordinate merge, sprint

#124 Update scatwind GeoVaLs reordering and use levels_minus_one
  testinput_tier_1/scatwind_geoval_20201001T0600Z.nc4
  testinput_tier_1/scatwind_geoval_small_20201001T0600Z.nc4
  testinput_tier_1/scatwind_geoval_small_reversed_20201001T0600Z.nc4
  testinput_tier_1/scatwind_obs_1d_small_2020100106.nc4
Labels: coordinate merge, ready for merge

#121 flip geovals for sattcwv so they are top down
  testinput_tier_1/sattcwv_geovals_20201230T0600Z.nc4
  testinput_tier_1/sattcwv_geovals_reversed_20201230T0600Z.nc4
Labels: ready for merge

#123 Change geoval ordering to top to bottom and rename vertical coords
  testinput_tier_1/satwind_geoval_20201001T0600Z.nc4
  testinput_tier_1/satwind_geoval_small_20201001T0600Z.nc4
  testinput_tier_1/satwind_geoval_small_reversed_20201001T0600Z.nc4
  testinput_tier_1/satwind_obs_1d_small_2020100106_noinv.nc4
Labels: coordinate merge

#127 Change geovals files for AodMetOffice in line with top-down model levels
  testinput_tier_1/aod_geoval_20210521T1200Z_mo.nc4
  testinput_tier_1/aod_geoval_reversed_20210521T1200Z_mo.nc4
Labels: coordinate merge, ready for merge

#128 Make top-down geovals the default for identity operator
  testinput_tier_1/sondes_background_error_vert_interp_air_pressure_geoval_2018041500_s.nc4
  testinput_tier_1/sondes_background_error_vert_interp_height_geoval_2018041500_s.nc4
  testinput_tier_1/sondes_geoval_2018041500_s.nc4
  testinput_tier_1/sondes_geoval_2018041500_s_reversed.nc4
Labels: coordinate merge, ready for merge, sprint

#131 Feature/rttov scatt update
  testinput_tier_1/atovs_metopb_obs_2021011512_rttov_scatt.nc4
  testinput_tier_1/geovals_atovs_20210115T1200Z_rttov_scatt.nc4
Labels: coordinate merge

#132 Feature/flipping geovals gbgnssoper
  testinput_tier_1/groundgnss_geovals_20191230T0600Z.nc4
  testinput_tier_1/groundgnss_geovals_reversed_20191230T0600Z.nc4
Labels: coordinate merge, ready for merge, sprint

#135 addition of surface_pressure_obserror TestReference
  testinput_tier_1/sfc_obs_2018041500_metars_small.nc
Labels: OBS1

#119 Add a new file for new specific_humidity variable transform (using dewpoint_temperature instead of RH)
  testinput_tier_1/instruments/conventional/buoy_wmo_multi.nc
Labels: OBS3
