Repository JCSDA-internal/ufo-data, pull requests merged in 2022-12, with the labels that each got.

#273 SPRINT: Update files so more operator tests pass
  testinput_tier_1/mopitt_co_2020090318_m.nc4
  testinput_tier_1/radar_dbz_obs_2019052222.nc4
  testinput_tier_1/radar_rw_obs_2020101300_m.nc4
  testinput_tier_1/tropomi_no2_total_2020090318_m.nc4
  testinput_tier_1/tropomi_no2_tropo_2020090318_m.nc4
Labels: coordinate merge, ready for merge, sprint

#267 File for poisson disk thinning update
  testinput_tier_1/met_office_poisson_disk_thinning.nc4
Labels: sprint

#275 SPRINT: Tidy up 1dvar names
  testinput_tier_1/atms_n20_obs_20191230T0000_rttov.nc4
  testinput_tier_1/atms_n20_obs_20191230T0000_setsurface_default.nc4
  testinput_tier_1/atovs_obs_2021011512_multiplatform.nc4
Labels: sprint

#265 Test files for TROPOMI CO
  testinput_tier_1/tropomi_co_geoval_2021081518_m.nc4
  testinput_tier_1/tropomi_co_total_2021081518_m.nc4
Labels: COMPO
