Repository JCSDA-internal/ufo-data, pull requests merged in 2022-08, with the labels that each got.

#193 add test data file for virtual temp variable transformation
  testinput_tier_1/2020100106_metars_small.nc
Labels: coordinate merge, OBS

#203 Modification of QNH to QFE variable transform data
  testinput_tier_1/QFEtoQNH_obs_20210521T1200Z.nc4
Labels: ready for merge

#205 Allow Met Office GNSS-RO operator to accept 2D arrays
  testinput_tier_1/gnssro_geoval_20210701T1200Z_profile.nc4
  testinput_tier_1/gnssro_obs_20210701T1200Z_profile.nc4
Labels: OBS

#207 Feature/gencol hofx part1
  testinput_tier_1/mopitt_co_2020090318_m.nc4
  testinput_tier_1/tropomi_no2_2020090318_m.nc4
  testinput_tier_1/tropomi_no2_total_2020090318_m.nc4
  testinput_tier_1/tropomi_no2_tropo_2020090318_m.nc4
Labels: ready for merge
