Repository JCSDA-internal/ufo-data, pull requests merged in 2022-11, with the labels that each got.

#229 Data for average temperature filter
  testinput_tier_1/gnssro_geoval_2018041500_3prof_avtemp.nc4
  testinput_tier_1/gnssro_obs_2018041500_3prof_avtemp.nc4
Labels: ready for merge, OBS

#257 Sprint: First 3 files hand-edited CDL updates
  testinput_tier_1/geos.mhs_metop-b_obs.2020121500_m.nc4
  testinput_tier_1/iasi_metop-a_obs_2018041500_m_qc.nc4
  testinput_tier_1/iasi_metop-a_obs_2018041500_m_unittest.nc4
Labels: draft, sprint

#246 Sprint groundgnss, aod, sattcwv, gauss thin and stringmanip test data changes
  testinput_tier_1/aod_obs_20210521T1200Z_mo.nc4
  testinput_tier_1/groundgnss_obs_2019123006_obs.nc
  testinput_tier_1/met_office_gauss_thinning_groundgnss_obs.nc4
  testinput_tier_1/met_office_gauss_thinning_groundgnssnames_obs.nc4
  testinput_tier_1/met_office_gauss_thinning_lon_-180_to_180_obs.nc4
  testinput_tier_1/met_office_gauss_thinning_lon_0_to_360_obs.nc4
  testinput_tier_1/sattcwv_obs_20201230T0600Z.nc4
  testinput_tier_1/stringmanipulation_obs.nc4
Labels: waiting for another PR, sprint

#261 Sprint: Another 6 files edited to remove deprecated VarMetaData group
  testinput_tier_1/QFEtoQNH_obs_20210521T1200Z.nc4
  testinput_tier_1/RadToBT_obs_2021071200.nc4
  testinput_tier_1/amsua_n19_obs_2018041500_m_with_diag_flags.nc4
  testinput_tier_1/aod_obs_2018041500_m.nc4
  testinput_tier_1/atms_n20_obs_20191230T0000_rttov_biaspred_redo_scan.nc4
  testinput_tier_1/gmi_gpm_obs_2018041500_m.nc4
  testinput_tier_1/gmi_gpm_obs_2020111500.nc4
  testinput_tier_1/gmi_gpm_obs_2020120100_m.nc4
  testinput_tier_1/gmi_gpm_obs_2020121500_m.nc4
Labels: OBS, sprint

#258 SPRINT: Updates to fix remaining rttov tests that were failing
  testinput_tier_1/atms_n20_obs_20191230T0000_rttov_bad_data.nc4
  testinput_tier_1/obs_ssmis_onedvar_20210701T1200Z.nc4
Labels: coordinate merge, ready for merge, sprint

#264 SPRINT: Some more variables transform ctests passing
  testinput_tier_1/RadToBT_obs_2021071200.nc4
  testinput_tier_1/scatwind_obs_2d_2020100106.nc4
  testinput_tier_1/wind_unit_transforms_2018041500.nc4
Labels: coordinate merge, ready for merge, sprint

#271 Update two wind test files used for wind variable transform ctest naming changes
  testinput_tier_1/wind_unit_transforms_2018041500.nc4
  testinput_tier_1/wind_unit_transforms_missing_values_2018041500.nc4
Labels: ready for merge, sprint

#269 Fix several unit tests
  testinput_tier_1/function_select_testdata.nc4
  testinput_tier_1/met_office_conventional_profile_processing_rh.nc4
  testinput_tier_1/radar_rw_obs_2020101300_m.nc4
Labels: sprint
