Repository JCSDA-internal/ufo-data, pull requests merged in 2022-09, with the labels that each got.

#212 DrawFromFile: Update to allow the highest index with the nearest method
  testinput_tier_1/drawvaluefromfile_simple.csv
  testinput_tier_1/variable_assignment_testdata.nc
Labels: needs review, OBS

#211 CloudFirstGuessMinimumResidual: update the iasi test for bugfix
  testinput_tier_1/iasi_metopb_obs_2021011500.nc4
Labels: bug, needs review, OBS

#192 Test data for Ocean Conversions
  testinput_tier_1/oceanprofile_theta_pressure_testdata.nc4
Labels: needs review

#214 Add new file for string manipualtion ctests
  testinput_tier_1/stringmanipulation_obs.nc4
Labels: waiting for another PR
