Repository JCSDA-internal/ufo-data, pull requests merged in 2023-05, with the labels that each got.

#324 Feature/sprint vertinterp
  testinput_tier_1/mopitt_co_2020090318_m.nc4
  testinput_tier_1/mopitt_co_geoval_2020090318_m.nc4
  testinput_tier_1/ompsnp_npp_obs_2019101700_m_colret.nc4
  testinput_tier_1/profile_2018-04-15_geovals.nc
  testinput_tier_1/tropomi_co_total_2021081518_m.nc4
  testinput_tier_1/tropomi_no2_total_2020090318_m.nc4
  testinput_tier_1/tropomi_no2_tropo_2020090318_m.nc4
Labels: code sprint

#328 Poisson disk thinning filter OPS compatibility mode option test reference data
  testinput_tier_1/met_office_poisson_disk_thinning_sort.nc4
Labels: ready for merge, OBS

#333 Add a data file for obsvalue predictor test
  testinput_tier_1/aod_obs_2018041500_m_predictors.nc4
Labels: OBS, COMPO

#326 Test data for ObsFunction to find model level height above measured cloud base height
  testinput_tier_1/met_office_surfacecloud_cloud_base_height_check.nc4
  testinput_tier_1/met_office_surfacecloud_cloud_base_height_check_geovals.nc4
Labels: ready for merge
