Repository JCSDA-internal/ufo-data, pull requests merged in 2023-04, with the labels that each got.

#319 Change ocean profile geovals to include depth variable
  testinput_tier_1/profile_2018-04-15_geovals.nc
Labels: OBS, code sprint

#323 add 2d structures in column operator
  testinput_tier_1/mopitt_co_2020090318_m.nc4
  testinput_tier_1/mopitt_co_geoval_2020090318_m.nc4
  testinput_tier_1/tropomi_co_total_2021081518_m.nc4
  testinput_tier_1/tropomi_no2_total_2020090318_m.nc4
  testinput_tier_1/tropomi_no2_tropo_2020090318_m.nc4
Labels: OBS, COMPO

#312 Make variable names conform for ufo-data
  testinput_tier_1/airs_aqua_20210701T1200Z_geovals_obfn_setsurface.nc4
  testinput_tier_1/amsr2_geovals_20191230T0000Z_100subset.nc4
  testinput_tier_1/atms_geovals_20200401T0000Z_10locs.nc4
  testinput_tier_1/geovals_atms_20191230T0000Z_benchmark.nc4
  testinput_tier_1/geovals_atms_20200401T0000Z_allsurfacetypes.nc4
  testinput_tier_1/geovals_atovs_20210115T1200Z_multiplatform.nc4
  testinput_tier_1/geovals_atovs_20210115T1200Z_rttov_scatt.nc4
  testinput_tier_1/geovals_atovs_20210115T1200Z_seaice.nc4
  testinput_tier_1/geovals_atovs_lwpguess_20210701T1200Z.nc4
  testinput_tier_1/geovals_atovs_transmittance_20210701T1200Z.nc4
  testinput_tier_1/geovals_ssmis_onedvar_20210701T1200Z.nc4
  testinput_tier_1/gnssro_geoval_20210701T1200Z_profile.nc4
  testinput_tier_1/groundgnss_geovals_20191230T0600Z.nc4
  testinput_tier_1/groundgnss_geovals_reversed_20191230T0600Z.nc4
  testinput_tier_1/met_office_conventional_profile_processing_average_geovals.nc4
  testinput_tier_1/met_office_conventional_profile_processing_average_geovals_extended.nc4
  testinput_tier_1/met_office_conventional_profile_processing_average_geovals_extended_reversed.nc4
  testinput_tier_1/met_office_conventional_profile_processing_average_single_profile_geovals.nc4
  testinput_tier_1/met_office_conventional_profile_processing_profileaverageobs_geovals.nc4
  testinput_tier_1/met_office_conventional_profile_processing_profileaverageobs_geovals_reversed.nc4
  testinput_tier_1/mhs_n19_geoval_2018041500_m_qc.nc4
  testinput_tier_1/sattcwv_geovals_20201230T0600Z.nc4
  testinput_tier_1/sattcwv_geovals_reversed_20201230T0600Z.nc4
Labels: waiting for other repos, coordinate merge
