Repository JCSDA-internal/ufo-data, pull requests merged in 2023-09, with the labels that each got.

#364 Add TestReference for new ReadBias predictor
  testinput_tier_1/aod_obs_2018041500_m_predictors.nc4
  testinput_tier_1/iasi_metopb_obs_2021011500.nc4
Labels: coordinate merge, do not merge

#370 Rename saturation specific humidity in geos test files
  testinput_tier_1/instruments/conventional/geos_sfcship_geoval_2020121500.nc4
  testinput_tier_1/instruments/conventional/geos_sondes_geoval_2020121500.nc4
Labels: coordinate merge

#371 Feature/add aircraft predictors
  testinput_tier_1/aircraft_obs_20190801T0000Z_aircraft_predictors.nc4
Labels: code sprint

#372 Update satellite VarBC files for new format
  testinput_tier_1/aircraft_artificial_bias.nc4
  testinput_tier_1/aircraft_artificial_bias_2.nc4
  testinput_tier_1/geos.bc.mhs_metop-b.2020121500.satbias.nc4
  testinput_tier_1/geos_satbias_amsua_n19.nc4
  testinput_tier_1/geos_satbias_atms_n20.nc4
  testinput_tier_1/gmi_gpm.20201214_21z.satbias.nc4
  testinput_tier_1/instruments/radiance/satbias_abi_g16.2021051618.nc4
  testinput_tier_1/instruments/radiance/satbias_airs_aqua.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_amsua_aqua.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_amsua_metop-a.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_amsua_metop-b.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_amsua_metop-c.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_amsua_n15.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_amsua_n18.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_amsua_n19.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_atms_n20.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_atms_npp.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_avhrr3_metop-a.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_avhrr3_n18.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_cris-fsr_n20.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_cris-fsr_npp.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_iasi_metop-a.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_iasi_metop-b.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_mhs_metop-b.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_mhs_metop-c.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_mhs_n19.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_seviri_m11.2020110106.nc4
  testinput_tier_1/instruments/radiance/satbias_ssmis_f17.nc4
  testinput_tier_1/satbias_airs_aqua.nc4
  testinput_tier_1/satbias_amsr2_gcom-w1.nc4
  testinput_tier_1/satbias_amsua_n19.nc4
  testinput_tier_1/satbias_amsua_n19_test1.nc4
  testinput_tier_1/satbias_amsua_n19_test2.nc4
  testinput_tier_1/satbias_amsua_n19_test3.nc4
  testinput_tier_1/satbias_amsua_n19_test4.nc4
  testinput_tier_1/satbias_amsua_n19_test5.nc4
  testinput_tier_1/satbias_amsua_n19_test6.nc4
  testinput_tier_1/satbias_atms_npp.nc4
  testinput_tier_1/satbias_cris-fsr_n20.nc4
  testinput_tier_1/satbias_cris-fsr_npp.nc4
  testinput_tier_1/satbias_iasi_metop-a.nc4
  testinput_tier_1/test_cov_satbias_amsua_n19.nc4
Labels: OBS, code sprint

#367 Update for bt to radiance variable transform change.
  testinput_tier_1/RadToBT_obs_2021071200.nc4
Labels: coordinate merge, UKMO

#374 place holder ufo-data for files needed for aircraft bc tests
  testinput_tier_1/aircraft_bias_20230913T00Z.nc4
Labels: coordinate merge, OBS, code sprint

#373 Adding geovals and obs files for tropics ufo ctest
  testinput_tier_1/tms_tropics-01_geovals_2022021600.nc4
  testinput_tier_1/tms_tropics-01_obs_2022021600.nc4
Labels: coordinate merge, OBS
