Repository JCSDA-internal/ufo-data, pull requests merged in 2024-07, with the labels that each got.

#426 New Obs and GeoVaLs files are needed to test the MPAS model with MRMS radar reflectivity and the OU-CAPS operator
  testinput_tier_1/geovals-mpas.mrms_reflectivity.20220216T000000Z_s.nc
  testinput_tier_1/obs.mrms_reflectivity.20220216T000000Z_s.nc
Labels: coordinate merge, ready for merge, OBS

#432 Add missing data for ufo changes to Arithmetic and RadToBT variable transform
  testinput_tier_1/RadToBT_obs_2021071200.nc4
Labels: ready for merge, UKMO

#431 File for radar edge detection OPS compatibility mode
  testinput_tier_1/radar_edge_flag.nc
Labels: coordinate merge, ready for merge, UKMO

#434 Variable Assignment: add extra reference variables for datetime to numeric conversion
  testinput_tier_1/variable_assignment_testdata.nc
Labels: coordinate merge, ready for merge, UKMO
