Repository JCSDA-internal/ufo-data, pull requests merged in 2024-08, with the labels that each got.

#435 Update filter_testdata to add more reference variables
  testinput_tier_1/filters_testdata.nc4
Labels: OBS

#433 Files for MO reflectivity operator test
  testinput_tier_1/radar_reflectivity_metoffice_geovals.nc4
  testinput_tier_1/radar_reflectivity_metoffice_obs.nc4
Labels: needs review, coordinate merge, UKMO

#436 UKMO rename qcl and qcf
  testinput_tier_1/airs_aqua_20210701T1200Z_geovals_obfn_setsurface.nc4
  testinput_tier_1/amsr2_geovals_20191230T0000Z_100subset.nc4
  testinput_tier_1/atms_geovals_20200401T0000Z_10locs.nc4
  testinput_tier_1/geovals_atms_20191230T0000Z_benchmark.nc4
  testinput_tier_1/geovals_atms_20191230T0000Z_benchmark_tolerance.nc4
  testinput_tier_1/geovals_atms_20200401T0000Z_allsurfacetypes.nc4
  testinput_tier_1/geovals_atovs_20210115T1200Z_multiplatform.nc4
  testinput_tier_1/geovals_atovs_20210115T1200Z_rttov_scatt.nc4
  testinput_tier_1/geovals_atovs_20210115T1200Z_seaice.nc4
  testinput_tier_1/geovals_atovs_lwpguess_20210701T1200Z.nc4
  testinput_tier_1/geovals_atovs_transmittance_20210701T1200Z.nc4
  testinput_tier_1/geovals_gmihigh_20210701T1200Z_out_0000_m.nc4
  testinput_tier_1/geovals_ssmis_onedvar_20210701T1200Z.nc4
  testinput_tier_1/gnssro_geoval_20210701T1200Z_profile.nc4
  testinput_tier_1/groundgnss_geovals_20191230T0600Z.nc4
  testinput_tier_1/groundgnss_geovals_reversed_20191230T0600Z.nc4
  testinput_tier_1/radar_reflectivity_metoffice_geovals.nc4
  testinput_tier_1/sattcwv_geovals_20201230T0600Z.nc4
  testinput_tier_1/sattcwv_geovals_reversed_20201230T0600Z.nc4
Labels: coordinate merge, UKMO

#439 Add test files for logarithm obs operator
  testinput_tier_1/logarithm_geovals.nc4
  testinput_tier_1/logarithm_obs.nc4
Labels: coordinate merge, UKMO

#442 Test data for model level index ObsFunction
  testinput_tier_1/model_level_index_geovals.nc
  testinput_tier_1/model_level_index_obs.nc4
Labels: coordinate merge, OBS, UKMO

#444 Add test file for logarithm variable transform
  testinput_tier_1/logarithm_transform_obs.nc4
Labels: coordinate merge, UKMO

#437 Revisions of the AOP/AodExt observation operator
  testinput_tier_1/nnr_aod_3ch_obs_2018041500_m.nc4
  testinput_tier_1/nnr_aod_3ch_obs_log_2018041500_m.nc4
Labels: coordinate merge, ready for merge, COMPO

#438 Update Doppler wind test file
  testinput_tier_1/radar_doppler_wind_geovals.nc4
Labels: coordinate merge, UKMO
